### ISSUE TITLE
Game cursor over the cockpit and HUD

### ISSUE THREAD

**Issue by xan2622** [debugcom/Hacking-F117A#2]
Hi. 👋

Your Github repository tells me that you are a passionate and probably (like I am) nostalgic of some of these MS-DOS games. 
I discovered F-19 and F-117A during my young years and I am in the process of replaying some of these good flight simulation games of the 90s.

I am barely a developer but I am working on a [AHK v2 script](https://github.com/xan2622/F-117A-Clickable-Cockpit) that allows to use the mouse cursor to click on the cockpit buttons of **F-117A Nighthawk Stealth Fighter 2.0**.

For the moment, if I have been able to use the mouse cursor to click on cockpit buttons, I haven't found the way to display the mouse cursor itself (because of [DOSBox](https://www.dosbox.com/) that "catches it" as soon as you click on its window). I am investigating the possible solutions to remedy this issue, such as using [DOSBox-X](https://dosbox-x.com/).

I don't know if this is possible but another solution would be to mod the game so that it is possible to display the ingame mouse cursor over the cockpit view (and not only while navigating the game menus (briefing, weapons selection, etc)).

👉 Do you know if it's possible to display the game cursor (the one that we see on the briefing screen) over the cockpit and HUD?

Mock-up: 
![Cursor01](https://github.com/debugcom/Hacking-F117A/assets/1732773/6607dd37-80ad-4fc4-a319-ff021380b9b6)

**Comment by debugcom** [comment]
Hi, sorry for the late reply ...

Yes it should be possible - the game itself shows and hides the mouse cursor as needed after all.
A quick search [here](https://github.com/FDOS/mouse/blob/master/int33.lst) tells me that to access the mouse cursor services in DOS, you need to call int 33h
1/ with the value 1 in the AX register, to show the cursor
2/ with the value 2 in the AX register, to hide the cursor

Not sure how you would call this from Autohotkey though.

**Comment by xan2622** [comment]
Hi. Thank you for your answer. I will investigate your solution. Thank you very much.
btw, I managed to display a mouse cursor with my AHK script.
